version: "3.8"
services:
  home-assistant:
    container_name: home-assistant
   # env_file:
    #  - stack.env
    image: homeassistant/home-assistant:2022.5.4
    restart: always
    volumes:
      - home-assistant_Config:/config
      - home-assistant_data:/media
    # depends_on:
    #   - postgres
    ports:
      - 8123:8123
      - 1400:1400
    networks:
      - network-iot_default
      - network-managment_default
  # postgres:
  #   container_name: postgres
  #   env_file: stack.env
  #   image: postgres:12.6
  #   restart: always
  #   networks:
  #     - localnet
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_DB: homeassistant
  #     POSTGRES_USER: ha_user
  #     POSTGRES_PASSWORD: CrazyStr0ngPa$$word

networks:
  network-iot_default:
    external: true
  network-managment_default:
    external: true

volumes:
  home-assistant_config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /pool_raid0/docker/config/home-assistant
  home-assistant_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /pool_raid0/docker/data/home-assistant
