version: "2.1"
volumes:
  unifi_config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /pool_raid0/docker/config/unifi/config
services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unifi-controller
    env_file:
    - stack.env
    environment:
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      #- /mnt/Toshiba1TB/srv/containerdata/UnifiController:/config
      - unifi_config:/config
    ports:
      - 8443:8443
      - 8080:8080
      #- 3478:3478/udp
      #- 10001:10001/udp
      #- 1900:1900/udp #optional
      #- 8843:8843 #optional
      #- 8880:8880 #optional
      #- 6789:6789 #optional
      #- 5514:5514/udp #optional
    restart: unless-stopped
